// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function Make(P) {
  return {
          value: P.constant
        };
}

var _ignore = 0;

exports.Make = Make;
exports._ignore = _ignore;
/* No side effect */
