// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function Make(P) {
  return {
          value: P.constant
        };
}

var Broken = {
  Make: Make
};

function Make$1(P) {
  return {
          value: P.constant
        };
}

var Works = {
  Make: Make$1
};

var _ignore = 0;

exports.Broken = Broken;
exports.Works = Works;
exports._ignore = _ignore;
/* No side effect */
